/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdCommonRouteImport } from './routes/p.$projectId.common'
import { Route as PProjectIdLinesLineNumberRouteImport } from './routes/p.$projectId.lines.$lineNumber'
import { Route as PProjectIdLinesLineNumberIndexRouteImport } from './routes/p.$projectId.lines.$lineNumber.index'
import { Route as PProjectIdLinesLineNumberEquipmentKindRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind'
import { Route as PProjectIdLinesLineNumberEquipmentKindIndexRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind.index'
import { Route as PProjectIdLinesLineNumberEquipmentKindPaRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind.pa'
import { Route as PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind.$equipmentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/p/$projectId/',
  path: '/p/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdCommonRoute = PProjectIdCommonRouteImport.update({
  id: '/p/$projectId/common',
  path: '/p/$projectId/common',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdLinesLineNumberRoute =
  PProjectIdLinesLineNumberRouteImport.update({
    id: '/p/$projectId/lines/$lineNumber',
    path: '/p/$projectId/lines/$lineNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const PProjectIdLinesLineNumberIndexRoute =
  PProjectIdLinesLineNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdLinesLineNumberRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindRoute =
  PProjectIdLinesLineNumberEquipmentKindRouteImport.update({
    id: '/equipment/$kind',
    path: '/equipment/$kind',
    getParentRoute: () => PProjectIdLinesLineNumberRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindIndexRoute =
  PProjectIdLinesLineNumberEquipmentKindIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdLinesLineNumberEquipmentKindRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindPaRoute =
  PProjectIdLinesLineNumberEquipmentKindPaRouteImport.update({
    id: '/pa',
    path: '/pa',
    getParentRoute: () => PProjectIdLinesLineNumberEquipmentKindRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute =
  PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport.update({
    id: '/$equipmentId',
    path: '/$equipmentId',
    getParentRoute: () => PProjectIdLinesLineNumberEquipmentKindRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberRouteWithChildren
  '/p/$projectId/lines/$lineNumber/': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/pa': typeof PProjectIdLinesLineNumberEquipmentKindPaRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/pa': typeof PProjectIdLinesLineNumberEquipmentKindPaRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberRouteWithChildren
  '/p/$projectId/lines/$lineNumber/': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/pa': typeof PProjectIdLinesLineNumberEquipmentKindPaRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/users'
    | '/p/$projectId/common'
    | '/p/$projectId/'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/pa'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/users'
    | '/p/$projectId/common'
    | '/p/$projectId'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/pa'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/users'
    | '/p/$projectId/common'
    | '/p/$projectId/'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/pa'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  PProjectIdCommonRoute: typeof PProjectIdCommonRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdLinesLineNumberRoute: typeof PProjectIdLinesLineNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/common': {
      id: '/p/$projectId/common'
      path: '/p/$projectId/common'
      fullPath: '/p/$projectId/common'
      preLoaderRoute: typeof PProjectIdCommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/lines/$lineNumber': {
      id: '/p/$projectId/lines/$lineNumber'
      path: '/p/$projectId/lines/$lineNumber'
      fullPath: '/p/$projectId/lines/$lineNumber'
      preLoaderRoute: typeof PProjectIdLinesLineNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/lines/$lineNumber/': {
      id: '/p/$projectId/lines/$lineNumber/'
      path: '/'
      fullPath: '/p/$projectId/lines/$lineNumber/'
      preLoaderRoute: typeof PProjectIdLinesLineNumberIndexRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind'
      path: '/equipment/$kind'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind/': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind/'
      path: '/'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind/'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindIndexRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberEquipmentKindRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind/pa': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind/pa'
      path: '/pa'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind/pa'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindPaRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberEquipmentKindRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberEquipmentKindRoute
    }
  }
}

interface PProjectIdLinesLineNumberEquipmentKindRouteChildren {
  PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute: typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
  PProjectIdLinesLineNumberEquipmentKindPaRoute: typeof PProjectIdLinesLineNumberEquipmentKindPaRoute
  PProjectIdLinesLineNumberEquipmentKindIndexRoute: typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
}

const PProjectIdLinesLineNumberEquipmentKindRouteChildren: PProjectIdLinesLineNumberEquipmentKindRouteChildren =
  {
    PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute:
      PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute,
    PProjectIdLinesLineNumberEquipmentKindPaRoute:
      PProjectIdLinesLineNumberEquipmentKindPaRoute,
    PProjectIdLinesLineNumberEquipmentKindIndexRoute:
      PProjectIdLinesLineNumberEquipmentKindIndexRoute,
  }

const PProjectIdLinesLineNumberEquipmentKindRouteWithChildren =
  PProjectIdLinesLineNumberEquipmentKindRoute._addFileChildren(
    PProjectIdLinesLineNumberEquipmentKindRouteChildren,
  )

interface PProjectIdLinesLineNumberRouteChildren {
  PProjectIdLinesLineNumberIndexRoute: typeof PProjectIdLinesLineNumberIndexRoute
  PProjectIdLinesLineNumberEquipmentKindRoute: typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
}

const PProjectIdLinesLineNumberRouteChildren: PProjectIdLinesLineNumberRouteChildren =
  {
    PProjectIdLinesLineNumberIndexRoute: PProjectIdLinesLineNumberIndexRoute,
    PProjectIdLinesLineNumberEquipmentKindRoute:
      PProjectIdLinesLineNumberEquipmentKindRouteWithChildren,
  }

const PProjectIdLinesLineNumberRouteWithChildren =
  PProjectIdLinesLineNumberRoute._addFileChildren(
    PProjectIdLinesLineNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  PProjectIdCommonRoute: PProjectIdCommonRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdLinesLineNumberRoute: PProjectIdLinesLineNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
