/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdIndexRouteImport } from './routes/p.$projectId.index'
import { Route as PProjectIdCommonRouteImport } from './routes/p.$projectId.common'
import { Route as PProjectIdLinesLineNumberRouteImport } from './routes/p.$projectId.lines.$lineNumber'
import { Route as PProjectIdLinesLineNumberIndexRouteImport } from './routes/p.$projectId.lines.$lineNumber.index'
import { Route as PProjectIdLinesLineNumberEquipmentKindRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind'
import { Route as PProjectIdLinesLineNumberEquipmentKindIndexRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind.index'
import { Route as PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport } from './routes/p.$projectId.lines.$lineNumber.equipment.$kind.$equipmentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdIndexRoute = PProjectIdIndexRouteImport.update({
  id: '/p/$projectId/',
  path: '/p/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdCommonRoute = PProjectIdCommonRouteImport.update({
  id: '/p/$projectId/common',
  path: '/p/$projectId/common',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdLinesLineNumberRoute =
  PProjectIdLinesLineNumberRouteImport.update({
    id: '/p/$projectId/lines/$lineNumber',
    path: '/p/$projectId/lines/$lineNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const PProjectIdLinesLineNumberIndexRoute =
  PProjectIdLinesLineNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdLinesLineNumberRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindRoute =
  PProjectIdLinesLineNumberEquipmentKindRouteImport.update({
    id: '/equipment/$kind',
    path: '/equipment/$kind',
    getParentRoute: () => PProjectIdLinesLineNumberRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindIndexRoute =
  PProjectIdLinesLineNumberEquipmentKindIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PProjectIdLinesLineNumberEquipmentKindRoute,
  } as any)
const PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute =
  PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport.update({
    id: '/$equipmentId',
    path: '/$equipmentId',
    getParentRoute: () => PProjectIdLinesLineNumberEquipmentKindRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberRouteWithChildren
  '/p/$projectId/lines/$lineNumber/': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
  '/p/$projectId/lines/$lineNumber/equipment/$kind/': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/p/$projectId/common': typeof PProjectIdCommonRoute
  '/p/$projectId/': typeof PProjectIdIndexRoute
  '/p/$projectId/lines/$lineNumber': typeof PProjectIdLinesLineNumberRouteWithChildren
  '/p/$projectId/lines/$lineNumber/': typeof PProjectIdLinesLineNumberIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind': typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
  '/p/$projectId/lines/$lineNumber/equipment/$kind/': typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
  '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/p/$projectId/common'
    | '/p/$projectId/'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/p/$projectId/common'
    | '/p/$projectId'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/p/$projectId/common'
    | '/p/$projectId/'
    | '/p/$projectId/lines/$lineNumber'
    | '/p/$projectId/lines/$lineNumber/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/'
    | '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PProjectIdCommonRoute: typeof PProjectIdCommonRoute
  PProjectIdIndexRoute: typeof PProjectIdIndexRoute
  PProjectIdLinesLineNumberRoute: typeof PProjectIdLinesLineNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/': {
      id: '/p/$projectId/'
      path: '/p/$projectId'
      fullPath: '/p/$projectId/'
      preLoaderRoute: typeof PProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/common': {
      id: '/p/$projectId/common'
      path: '/p/$projectId/common'
      fullPath: '/p/$projectId/common'
      preLoaderRoute: typeof PProjectIdCommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/lines/$lineNumber': {
      id: '/p/$projectId/lines/$lineNumber'
      path: '/p/$projectId/lines/$lineNumber'
      fullPath: '/p/$projectId/lines/$lineNumber'
      preLoaderRoute: typeof PProjectIdLinesLineNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId/lines/$lineNumber/': {
      id: '/p/$projectId/lines/$lineNumber/'
      path: '/'
      fullPath: '/p/$projectId/lines/$lineNumber/'
      preLoaderRoute: typeof PProjectIdLinesLineNumberIndexRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind'
      path: '/equipment/$kind'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind/': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind/'
      path: '/'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind/'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindIndexRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberEquipmentKindRoute
    }
    '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId': {
      id: '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/p/$projectId/lines/$lineNumber/equipment/$kind/$equipmentId'
      preLoaderRoute: typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRouteImport
      parentRoute: typeof PProjectIdLinesLineNumberEquipmentKindRoute
    }
  }
}

interface PProjectIdLinesLineNumberEquipmentKindRouteChildren {
  PProjectIdLinesLineNumberEquipmentKindIndexRoute: typeof PProjectIdLinesLineNumberEquipmentKindIndexRoute
  PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute: typeof PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute
}

const PProjectIdLinesLineNumberEquipmentKindRouteChildren: PProjectIdLinesLineNumberEquipmentKindRouteChildren =
  {
    PProjectIdLinesLineNumberEquipmentKindIndexRoute:
      PProjectIdLinesLineNumberEquipmentKindIndexRoute,
    PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute:
      PProjectIdLinesLineNumberEquipmentKindEquipmentIdRoute,
  }

const PProjectIdLinesLineNumberEquipmentKindRouteWithChildren =
  PProjectIdLinesLineNumberEquipmentKindRoute._addFileChildren(
    PProjectIdLinesLineNumberEquipmentKindRouteChildren,
  )

interface PProjectIdLinesLineNumberRouteChildren {
  PProjectIdLinesLineNumberIndexRoute: typeof PProjectIdLinesLineNumberIndexRoute
  PProjectIdLinesLineNumberEquipmentKindRoute: typeof PProjectIdLinesLineNumberEquipmentKindRouteWithChildren
}

const PProjectIdLinesLineNumberRouteChildren: PProjectIdLinesLineNumberRouteChildren =
  {
    PProjectIdLinesLineNumberIndexRoute: PProjectIdLinesLineNumberIndexRoute,
    PProjectIdLinesLineNumberEquipmentKindRoute:
      PProjectIdLinesLineNumberEquipmentKindRouteWithChildren,
  }

const PProjectIdLinesLineNumberRouteWithChildren =
  PProjectIdLinesLineNumberRoute._addFileChildren(
    PProjectIdLinesLineNumberRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PProjectIdCommonRoute: PProjectIdCommonRoute,
  PProjectIdIndexRoute: PProjectIdIndexRoute,
  PProjectIdLinesLineNumberRoute: PProjectIdLinesLineNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
